export const GET_PLACES_REQUEST = "GET_PLACES_REQUEST";
export const GET_PLACES_SUCCESS = "GET_PLACES_SUCCESS";
export const GET_PLACES_FAILED = "GET_PLACES_FAILED";

export const POST_PLACES_REQUEST = "POST_PLACES_REQUEST";
export const POST_PLACES_SUCCESS = "POST_PLACES_SUCCESS";
export const POST_PLACES_FAILED = "POST_PLACES_FAILED";

export const DELETE_PLACES_REQUEST = "DELETE_PLACES_REQUEST";
export const DELETE_PLACES_SUCCESS = "DELETE_PLACES_SUCCESS";
export const DELETE_PLACES_FAILED = "DELETE_PLACES_FAILED";

export const UPDATE_PLACES_REQUEST = "UPDATE_PLACES_REQUEST";
export const UPDATE_PLACES_SUCCESS = "UPDATE_PLACES_SUCCESS";
export const UPDATE_PLACES_FAILED = "UPDATE_PLACES_FAILED";
